# Generated by Django 3.2.3 on 2021-05-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irrigate", "0006_auto_20210522_0158"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleday",
            options={"ordering": [["weekday", "month"]]},
        ),
        migrations.AlterUniqueTogether(
            name="scheduleday",
            unique_together={("month", "weekday")},
        ),
    ]
