# Generated by Django 3.2.3 on 2021-05-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irrigate", "0009_delete_scheduleday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actuatorrunlog",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
