# Generated by Django 3.2.4 on 2021-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irrigate", "0011_auto_20210801_0034"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletime",
            name="duration_in_minutes",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
