# Generated by Django 3.2.4 on 2025-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irrigate", "0013_scheduletime_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="actuator",
            name="grass_seed_mode",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, turns on for 1 minute every 5 hours daily",
            ),
        ),
    ]
